### ISSUE TITLE
I wanted a cat 😑

### ISSUE THREAD

**Issue by mohsinulhaq** [antonmedv/kot#1]
Instead, I got a kot.

**Comment by mohsinulhaq** [comment]
dead repo, doesn't address user concerns

**Comment by antonmedv** [comment]
What?! I’m working on cat already! You should donate me!!

**Comment by mohsinulhaq** [comment]
talk to me when the module starts returning cats

**Comment by antonmedv** [comment]
https://www.npmjs.com/package/cat-names
